"use client";

import { useState } from "react";
import { Sparkles, Calendar, Star, Moon, TrendingUp, BookOpen, Loader2, AlertCircle, Lock, User, Clock, MapPin } from "lucide-react";
import { zodiacSigns, getSignById, elementColors } from "@/lib/astrology/signs";
import { Eyebrow, Card, OrnateDivider, Tag } from "@/components/shared/ui-primitives";
import { cn } from "@/lib/utils";

type HoroscopeResponse = {
  type: string;
  date: string;
  sign: string | null;
  signName: string | null;
  signGlyph: string | null;
  content: string;
  mood: number;
  luckyNumber: number;
  luckyColor: string;
  themes: string[];
  transits: { transitPlanet: string; aspectType: string; natalPlanet: string; description: string; exact: boolean }[];
  retrogrades: string[];
  sources: { chapter_num: number; chapter_title: string; text: string; score?: number }[];
  personalized: boolean;
  cached?: boolean;
};

const COMMON_CITIES: Record<string, { name: string; lat: number; lng: number }> = {
  london: { name: "London, UK", lat: 51.5074, lng: -0.1278 },
  paris: { name: "Paris, France", lat: 48.8566, lng: 2.3522 },
  berlin: { name: "Berlin, Germany", lat: 52.52, lng: 13.405 },
  amsterdam: { name: "Amsterdam, Netherlands", lat: 52.3676, lng: 4.9041 },
  madrid: { name: "Madrid, Spain", lat: 40.4168, lng: -3.7038 },
  rome: { name: "Rome, Italy", lat: 41.9028, lng: 12.4964 },
  dublin: { name: "Dublin, Ireland", lat: 53.3498, lng: -6.2603 },
  stockholm: { name: "Stockholm, Sweden", lat: 59.3293, lng: 18.0686 },
  newyork: { name: "New York, USA", lat: 40.7128, lng: -74.006 },
  amman: { name: "Amman, Jordan", lat: 31.963, lng: 35.91 },
  dubai: { name: "Dubai, UAE", lat: 25.2048, lng: 55.2708 },
  istanbul: { name: "Istanbul, Turkey", lat: 41.0082, lng: 28.9784 },
};

const timeFrames = [
  { id: "daily", label: "Daily", icon: Star, desc: "Today's cosmic weather", premium: false },
  { id: "weekly", label: "Weekly", icon: Calendar, desc: "The week ahead", premium: true },
  { id: "monthly", label: "Monthly", icon: Moon, desc: "Month themes & key dates", premium: true },
  { id: "yearly", label: "Yearly", icon: TrendingUp, desc: "Year overview & cycles", premium: true },
] as const;

export default function AIHoroscopePage() {
  const [selectedSign, setSelectedSign] = useState("aries");
  const [timeFrame, setTimeFrame] = useState<"daily" | "weekly" | "monthly" | "yearly">("daily");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<HoroscopeResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showSources, setShowSources] = useState(false);

  // Birth data for personalization
  const [useBirthData, setUseBirthData] = useState(false);
  const [birthDate, setBirthDate] = useState("");
  const [birthTime, setBirthTime] = useState("");
  const [cityKey, setCityKey] = useState("london");

  const generate = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const payload: Record<string, unknown> = {
        type: timeFrame,
        sign: selectedSign,
      };

      if (useBirthData && birthDate) {
        const city = COMMON_CITIES[cityKey] || COMMON_CITIES.london;
        payload.birthDate = birthDate;
        payload.birthTime = birthTime || undefined;
        payload.lat = city.lat;
        payload.lng = city.lng;
        payload.birthPlace = city.name;
      }

      const response = await fetch("/api/horoscope/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.error || "Generation failed");
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not generate horoscope");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:py-16">
      <div className="mb-10 text-center">
        <Eyebrow>AI-Powered · Real Transits · Book-Grounded</Eyebrow>
        <h1 className="heading-serif mt-2 text-4xl font-semibold text-foreground sm:text-5xl">
          Personal Horoscope
        </h1>
        <p className="mt-3 text-sm text-foreground-muted">
          Generated by AI using real planetary positions and C.A.Q. Libra&apos;s classical text.
          Every reading is cached per sign per day — all Leos get the same daily reading.
        </p>
      </div>

      {/* Controls */}
      <Card className="mb-6 p-6">
        {/* Sign Picker */}
        <label className="mb-2 block text-xs uppercase tracking-wider text-foreground-subtle">
          <User className="inline h-3 w-3 mr-1" />
          Choose Your Sign
        </label>
        <div className="grid grid-cols-6 gap-1.5 sm:grid-cols-12">
          {zodiacSigns.map((sign) => (
            <button
              key={sign.id}
              onClick={() => setSelectedSign(sign.id)}
              className={cn(
                "flex flex-col items-center gap-0.5 rounded-lg border p-2 transition-all",
                selectedSign === sign.id
                  ? "border-primary bg-primary/5 text-primary"
                  : "border-border bg-surface text-foreground-muted hover:border-primary-light hover:bg-surface-muted"
              )}
            >
              <span className="text-lg">{sign.glyph}</span>
              <span className="text-[9px] font-medium">{sign.name.slice(0, 3)}</span>
            </button>
          ))}
        </div>

        {/* Birth Data Toggle */}
        <div className="mt-5 border-t border-border pt-4">
          <button
            onClick={() => setUseBirthData(!useBirthData)}
            className="flex w-full items-center justify-between"
          >
            <span className="flex items-center gap-2 text-sm font-medium text-foreground">
              <Lock className="h-3.5 w-3.5 text-primary" />
              Personalize with birth chart
              <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-medium text-primary">Premium</span>
            </span>
            <span className={cn("text-xs", useBirthData ? "text-primary" : "text-foreground-subtle")}>
              {useBirthData ? "ON" : "OFF"}
            </span>
          </button>

          {useBirthData && (
            <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
              <div>
                <label className="mb-1 flex items-center gap-1 text-xs text-foreground-muted">
                  <Calendar className="h-3 w-3" /> Birth Date
                </label>
                <input
                  type="date"
                  value={birthDate}
                  onChange={(e) => setBirthDate(e.target.value)}
                  max={new Date().toISOString().split("T")[0]}
                  min="1900-01-01"
                  className="input-field text-sm"
                />
              </div>
              <div>
                <label className="mb-1 flex items-center gap-1 text-xs text-foreground-muted">
                  <Clock className="h-3 w-3" /> Birth Time
                </label>
                <input
                  type="time"
                  value={birthTime}
                  onChange={(e) => setBirthTime(e.target.value)}
                  className="input-field text-sm"
                />
              </div>
              <div>
                <label className="mb-1 flex items-center gap-1 text-xs text-foreground-muted">
                  <MapPin className="h-3 w-3" /> Birth City
                </label>
                <select
                  value={cityKey}
                  onChange={(e) => setCityKey(e.target.value)}
                  className="input-field text-sm cursor-pointer"
                >
                  {Object.entries(COMMON_CITIES).map(([key, city]) => (
                    <option key={key} value={key}>{city.name}</option>
                  ))}
                </select>
              </div>
            </div>
          )}
        </div>

        {/* Time Frame */}
        <label className="mb-2 mt-5 block text-xs uppercase tracking-wider text-foreground-subtle">
          Time Frame
        </label>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {timeFrames.map((tf) => (
            <button
              key={tf.id}
              onClick={() => setTimeFrame(tf.id)}
              className={cn(
                "relative flex flex-col items-center gap-1 rounded-lg border p-3 transition-all",
                timeFrame === tf.id
                  ? "border-primary bg-primary/5"
                  : "border-border bg-surface hover:border-primary-light hover:bg-surface-muted"
              )}
            >
              <tf.icon className={cn("h-4 w-4", timeFrame === tf.id ? "text-primary" : "text-foreground-muted")} />
              <span className={cn("text-sm font-medium", timeFrame === tf.id ? "text-primary" : "text-foreground")}>
                {tf.label}
              </span>
              <span className="text-[10px] text-foreground-subtle">{tf.desc}</span>
              {tf.premium && (
                <span className="absolute -top-1.5 -right-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[8px] text-surface">
                  ✦
                </span>
              )}
            </button>
          ))}
        </div>

        <button onClick={generate} disabled={loading} className="btn-primary mt-5 w-full disabled:opacity-50">
          {loading ? (
            <><Loader2 className="h-4 w-4 animate-spin" /> Consulting the stars...</>
          ) : (
            <><Sparkles className="h-4 w-4" /> Generate {timeFrames.find((t) => t.id === timeFrame)?.label} Horoscope</>
          )}
        </button>
      </Card>

      {/* Error */}
      {error && (
        <Card className="mb-6 border-error/30 bg-error-light/50 p-4">
          <div className="flex items-center gap-2 text-sm text-error">
            <AlertCircle className="h-4 w-4" />
            {error}
          </div>
        </Card>
      )}

      {/* Result */}
      {result && (
        <div className="fade-in">
          <OrnateDivider className="mb-6" />

          {/* Header */}
          <div className="mb-6 flex items-center gap-4">
            {result.signGlyph && (
              <div
                className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full text-3xl"
                style={{ background: `${elementColors[getSignById(result.sign || "")?.element || "Fire"]}15` }}
              >
                {result.signGlyph}
              </div>
            )}
            <div className="flex-1">
              <h2 className="font-serif text-2xl font-semibold text-foreground">
                {result.signName} · {timeFrames.find((t) => t.id === result.type)?.label}
              </h2>
              <p className="text-xs text-foreground-subtle">
                {new Date(result.date).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}
                {result.personalized ? " · Personalized to your birth chart" : " · Sun-sign reading"}
                {result.cached && " · Cached (same for all " + result.signName + "s today)"}
              </p>
            </div>
          </div>

            {/* Reading */}
            <Card className="mb-4 p-6">
              <p className="text-base leading-relaxed text-foreground whitespace-pre-wrap">{result.content}</p>
            </Card>

            {/* Meta */}
            <div className="mb-4 flex flex-wrap gap-2">
              <Tag>Mood: {"★".repeat(result.mood)}{"☆".repeat(5 - result.mood)}</Tag>
              <Tag>Lucky number: {result.luckyNumber}</Tag>
              <Tag>Colour: {result.luckyColor}</Tag>
              {result.themes.map((t) => (
                <Tag key={t} className="bg-primary/5 text-primary">{t}</Tag>
              ))}
            </div>

            {/* Transits */}
            {result.transits.length > 0 && (
              <Card className="mb-4 p-5">
                <Eyebrow><TrendingUp className="inline h-3 w-3 mr-1" />Active Transits</Eyebrow>
                <ul className="mt-3 space-y-2">
                  {result.transits.map((t, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-foreground-muted">
                      <span className={cn("mt-0.5 shrink-0", t.exact ? "text-primary" : "text-foreground-subtle")}>
                        {t.exact ? "●" : "○"}
                      </span>
                      <span>{t.description}</span>
                    </li>
                  ))}
                </ul>
                {result.retrogrades.length > 0 && (
                  <p className="mt-3 border-t border-border pt-3 text-xs text-warning">
                    ⚠ {result.retrogrades.join(", ")} {result.retrogrades.length > 1 ? "are" : "is"} retrograde — review and reflect.
                  </p>
                )}
              </Card>
            )}

            {/* Sources */}
            {result.sources.length > 0 && (
              <Card className="p-5">
                <button
                  onClick={() => setShowSources(!showSources)}
                  className="flex w-full items-center justify-between text-left"
                >
                  <span className="flex items-center gap-1.5 text-sm font-medium text-primary">
                    <BookOpen className="h-4 w-4" />
                    Sourced from the book ({result.sources.length} passages)
                  </span>
                  <span className="text-xs text-foreground-subtle">{showSources ? "Hide" : "Show"}</span>
                </button>
                {showSources && (
                  <div className="mt-3 space-y-2">
                    {result.sources.map((s, i) => (
                      <div key={i} className="rounded-md bg-surface-muted/60 p-3">
                        <p className="mb-1 text-[10px] font-medium uppercase tracking-wider text-primary">
                          Ch.{s.chapter_num}: {s.chapter_title}
                          {s.score !== undefined && (
                            <span className="ml-2 text-foreground-subtle">{Math.round(s.score * 100)}% match</span>
                          )}
                        </p>
                        <p className="text-xs leading-relaxed text-foreground-muted line-clamp-3">
                          &ldquo;{s.text}&rdquo;
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </Card>
            )}
        </div>
      )}
    </div>
  );
}