import { Eyebrow } from "@/components/shared/ui-primitives";

export const metadata = {
  title: "Terms of Service",
  description: "Terms of service for Astrolo — the premium astrology PWA.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12 sm:px-6 lg:py-16">
      <div className="mb-8">
        <Eyebrow>Legal</Eyebrow>
        <h1 className="heading-serif mt-2 text-3xl font-semibold text-foreground">Terms of Service</h1>
        <p className="mt-2 text-sm text-foreground-muted">Last updated: August 2026</p>
      </div>

      <div className="space-y-6 text-sm leading-relaxed text-foreground-muted">
        <section>
          <h2 className="text-sm font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p className="mt-1">By using Astrolo, you agree to these terms. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">2. Description of Service</h2>
          <p className="mt-1">Astrolo provides astrology tools including natal chart calculation, horoscopes, AI-powered advisory, and a digitized astrology library. The free tier includes daily horoscopes and basic chart calculation. Premium features require a subscription.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">3. Subscription and Billing</h2>
          <p className="mt-1">Premium subscriptions are billed monthly or annually through Stripe. You can cancel at any time. No refunds for partial billing periods. Prices may vary by region (purchasing power parity pricing).</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">4. Entertainment Disclaimer</h2>
          <p className="mt-1">All astrological content is for entertainment and self-reflection purposes only. Astrolo does not provide medical, legal, financial, or psychological advice. Always consult qualified professionals for important decisions.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">5. AI-Generated Content</h2>
          <p className="mt-1">Some content (horoscopes, advisor responses) is generated by AI models. While we use classical astrology texts as a knowledge base, AI can make errors. Use your own judgment when interpreting readings.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">6. User Conduct</h2>
          <p className="mt-1">You agree not to: abuse the AI advisor, attempt to extract the knowledge base, scrape content at scale, or use the service for any illegal purpose.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">7. Intellectual Property</h2>
          <p className="mt-1">Astrolo&apos;s code, design, and original content are owned by Astrolo. The digitized book is from a public domain source (C.A.Q. Libra, 1917). AI-generated horoscopes are provided for personal use only.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">8. Privacy</h2>
          <p className="mt-1">See our <a href="/privacy" className="text-primary">Privacy Policy</a> for how we handle your data.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">9. Limitation of Liability</h2>
          <p className="mt-1">Astrolo is provided &ldquo;as is&rdquo; without warranties. We are not liable for any decisions made based on astrological readings.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">10. Changes to Terms</h2>
          <p className="mt-1">We may update these terms. Continued use after changes constitutes acceptance.</p>
        </section>

        <section>
          <h2 className="text-sm font-semibold text-foreground">11. Contact</h2>
          <p className="mt-1">For questions about these terms, contact <a href="mailto:hello@astrolo.app" className="text-primary">hello@astrolo.app</a>.</p>
        </section>
      </div>
    </div>
  );
}